### ISSUE TITLE
Forgotten Password Reset Not Open After Inserting the Command into the Run Prompt

### ISSUE THREAD

**Issue by 1532262** [ESIPFed/Geoweaver#316] opened 2022-09-01 01:28 UTC
I cannot execute on Geoweaver because I need a password. When trying to reset password into the run command, it opens a new window and closes it .1 seconds later. Anyone have any ideas?

**Comment by ZihengSun** [comment] 2022-09-01 21:47
@chetana1997 can you help take a look?

**Comment by chetana1997** [comment] 2022-09-02 00:20
Surely professor, I will take a look at the issue.

**Comment by chetana1997** [comment] 2022-09-02 23:22
Hello @1532262 ,

I am working on the password reset issue which you are currently facing.
I have checked in my local and the function works properly in my machine. Can you please provide your machine details including the OS type in order for me to investigate the reason in detail regarding why the issue is happening on your machine.

**Comment by 1532262** [comment] 2022-09-03 00:52
Laptop: HP Pavilion Aero Laptop 13-be0xxx
Device name	NicholasA
Processor	AMD Ryzen 7 5800U with Radeon Graphics            1.90 GHz
Installed RAM	16.0 GB (15.3 GB usable)
Device ID	8FE0640B-1EEB-4493-BFB0-95212B48C43A
Product ID	00342-21947-77183-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display


Edition	Windows 11 Home
Version	21H2
Installed on	‎6/‎9/‎2022
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0


I will try to reinstall geoweaver tomorrow and see what happens. Thanks

**Comment by ZihengSun** [comment] 2022-12-25 05:34
This might be an bug on the Windows 11. We only have Windows 10 to test on. It is a little bit hard to find a test machine.

**Closed** 2024-02-11 22:04 UTC
Labels: delay
